version: "3.3"
services:
    db:
        build: ./db
        container_name: db
        volumes:
            - ./db/data:/var/lib/mysql
    api:
        build: ./api
        container_name: api
        ports:
            - 3000:80
        volumes:
            - ./api/src:/usr/src/app
        depends_on:
            - db
        environment:
            - DATABASE_HOST=db
    web:
        build: ./web
        container_name: web
        ports:
            - 80:80
        volumes:
            - ./web/src:/usr/src/app
        depends_on:
            - db
        environment:
            - DATABASE_HOST=db
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.7
        container_name: phpmyadmin
        environment:
            - PMA_ARBITARY=1
        restart: always
        ports:
            - 8080:80
        volumes:
            - /sessions
        depends_on:
            - db
