version: "3.3"
services:
    api:
        build: ./api
        container_name: api
        ports:
            - 3000:80
        volumes:
            - ./api/src:/usr/src/app
        depends_on:
            - db
        environment:
            - DATABASE_HOST=db
    web:
        build: ./web
        container_name: web
        ports:
            - 80:80
        volumes:
            - ./web/src:/usr/src/app
        depends_on:
            - db
        environment:
            - DATABASE_HOST=db
    db:
        build: ./db
        container_name: db
        volumes:
            - ./db/data:/var/lib/mysql
    webold:
        build: ./webold
        container_name: webold
        ports:
            - 5001:80
        volumes:
            - ./webold/src:/var/www/html
            - ./webold/mods-enabled:/etc/apache2/mods-enabled
            - ./webold/mods-available:/etc/apache2/mods-available
        depends_on:
            - api
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.7
        container_name: phpmyadmin
        environment:
            - PMA_ARBITARY=1
        restart: always
        ports:
            - 8080:80
        volumes:
            - /sessions
