version: "3.3"
services:
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
        container_name: elastic
        environment:
            - cluster.name=ferrum-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        deploy:
            resources:
                limits:
                    memory: 1g
        volumes:
            - esdata:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        # networks:
            # - esnet
    db:
        build: ./db
        container_name: db
        volumes:
            - ./db/data:/var/lib/mysql

    api:
        build: ./api
        container_name: api
        ports:
            - 3000:80
        volumes:
            - ./api/src:/usr/src/app
        depends_on:
            - db
        environment:
            - DATABASE_HOST=db
    web:
        build: ./web
        container_name: web
        ports:
            - 80:80
        volumes:
            - ./web/src:/usr/src/app
        depends_on:
            - db
        environment:
            - DATABASE_HOST=db
        # networks:
        #     - esnet
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.7
        container_name: phpmyadmin
        environment:
            - PMA_ARBITARY=1
        restart: always
        ports:
            - 8080:80
        volumes:
            - /sessions
        depends_on:
            - db
volumes:
    esdata:
        driver: local
# networks:
#     esnet:
