[package]
name = "ferrum"
version = "0.1.0"
build = "build.rs"
edition = "2018"
exclude = ["artifacts.json", "addon.node"]

[lib]
name = "ferrum"
crate-type = ["cdylib"]

[build-dependencies]
napi-build = "1.0.0-alpha.0"

[dependencies]
napi = "1.0.0-alpha.4"
napi-derive = "1.0.0-alpha.0"
