[package]
name = "ferrum"
version = "0.2.0"
build = "build.rs"
edition = "2018"
exclude = ["artifacts.json", "addon.node"]

[lib]
name = "ferrum"
crate-type = ["cdylib"]

[build-dependencies]
napi-build = "1.0.1"

[dependencies]
napi = { version = "1.1.1", features = ["serde-json", "napi4"] }
napi-derive = "1.0.0"
tempfile = "3.2.0"
dirs = "3.0.1"
serde = { version = "1.0.120", features = ["derive"] }
serde_repr = "0.1.6"
serde_json = "1.0.61"
jemallocator = "0.3.2"
alphanumeric-sort = "1.4.0"
rodio = "0.13.0"
# tokio = "1.0.2"
